name:                echo-bot
version:             0.1.0.0
github:              "zloilya/echo-bot"
license:             BSD3
author:              "Ilya Baryshnikov"
maintainer:          "zlonast@gmal.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/echo-bot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- http-client
- http-client-tls
- bytestring
- postgresql-simple
- text-show
- random
- yaml
- deriving-aeson

default-extensions:
- DataKinds
- OverloadedStrings
- FlexibleContexts
- RecordWildCards
- RankNTypes
- TypeApplications
- ViewPatterns
- NamedFieldPuns

- DerivingStrategies
- GeneralizedNewtypeDeriving
- DeriveGeneric
- DeriveAnyClass
- DerivingVia

library:
  source-dirs: src

executables:
  echo-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echo-bot

tests:
  echo-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echo-bot
