name:                MetaLamp-telegram-bot
version:             0.1.0.0
github:              "githubuser/MetaLamp-telegram-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MetaLamp-telegram-bot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- lens
- lens-aeson
- text
- wai
- warp
- http-conduit
- http-types
- bytestring
- http-client
- uri-encode
- transformers
- postgresql-simple
- text-show

default-extensions:
- DataKinds
- DeriveGeneric
- FlexibleInstances
- OverloadedStrings
- ScopedTypeVariables
- DeriveAnyClass
- FlexibleContexts
- TypeOperators
- RecordWildCards

library:
  source-dirs: src

executables:
  MetaLamp-telegram-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MetaLamp-telegram-bot

tests:
  MetaLamp-telegram-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MetaLamp-telegram-bot
